#include<iostream>
#include<conio.h>
using  namespace  std;

int  main()
{
    int No1 = 0,  No2 = 0,  Sum = 0;

    cout << "\n Enter Number 1st = " ;
    cin >> No1;

    cout << "\n Enter Number 2nd = " ;
    cin >> No2;

    Sum = No1 + No2;

    cout << "\n Addition Of  " << No1 << " & " << No2 << " is = " << Sum << "." << endl ;
    cout << "\n Thanks...";

    getch();
    return 0;
}
